#!/usr/bin/env python3
"""
Turns the SADIE II first-order spherical-harmonic HRIR into Kotlin source.

Input is sh_hrir_order_1.wav, taken from Google's Resonance Audio repository at
third_party/SADIE_hrtf_database/WAV/Subject_002/SH/, Apache-2.0, with the licence kept
beside this script as LICENSE.SADIE. Four channels of 256 taps at 48 kHz: the ambisonic
(ACN/SN3D) binaural decode filters W, Y, Z, X, measured on a Neumann KU100 dummy head by
the Audio Lab at the University of York, diffuse-field corrected, left hemisphere only
because the set is symmetric.

Committed as generated Kotlin rather than as a binary asset on purpose. F-Droid's inclusion
policy refuses prebuilt binaries, and a table of numbers is source in a way a .wav is not.
The .wav is kept alongside only so the conversion can be checked; nothing reads it at build
time. Output is deterministic, so regenerating and diffing proves the table matches.

    python3 docs/hrtf/convert_sadie.py docs/hrtf/sh_hrir_order_1.wav \
        > app/src/main/java/com/dd3boh/outertune/playback/SadieHrir.kt
"""
import sys
import struct
import wave

NAMES = ["W", "Y", "Z", "X"]

ORDER_FOR_CHANNELS = {4: 1, 9: 2, 16: 3}


def main(path):
    w = wave.open(path)
    assert w.getsampwidth() == 2, "expected 16-bit samples"
    assert w.getframerate() == 48000, "expected 48 kHz"
    channels, taps = w.getnchannels(), w.getnframes()
    assert channels in ORDER_FOR_CHANNELS, "expected 4, 9 or 16 channels, got %d" % channels
    order = ORDER_FOR_CHANNELS[channels]
    raw = struct.unpack("<%dh" % (channels * taps), w.readframes(taps))
    chans = [[raw[f * channels + c] for f in range(taps)] for c in range(channels)]

    out = []
    out.append("/*")
    out.append(" * Copyright (C) 2026 InterTune")
    out.append(" *")
    out.append(" * SPDX-License-Identifier: GPL-3.0")
    out.append(" */")
    out.append("")
    out.append("package com.dd3boh.outertune.playback")
    out.append("")
    out.append("/**")
    out.append(" * SADIE II first-order ambisonic binaural decode filters, measured on a Neumann KU100.")
    out.append(" *")
    out.append(" * GENERATED by docs/hrtf/convert_sadie.py. Do not edit by hand.")
    out.append(" *")
    out.append(" * From Google's Resonance Audio, third_party/SADIE_hrtf_database/WAV/Subject_002/SH/")
    out.append(" * sh_hrir_order_1.wav, Apache License 2.0, kept at docs/hrtf/LICENSE.SADIE. Measured by")
    out.append(" * the Audio Lab at the University of York. %d channels in ACN order, %d taps at" % (channels, taps))
    out.append(" * 48 kHz, diffuse-field corrected, left hemisphere only because the set is symmetric.")
    out.append(" *")
    out.append(" * A table of numbers rather than an asset, because F-Droid will not accept a prebuilt")
    out.append(" * binary and this way the data is source like everything else.")
    out.append(" */")
    out.append("object SadieHrir {")
    out.append("    const val TAPS = %d" % taps)
    out.append("    const val SAMPLE_RATE = 48000")
    out.append("")
    for c in range(channels):
        name = NAMES[c]
        out.append("    /** ACN %d, %s. */" % (c, name))
        out.append("    val %s: ShortArray = shortArrayOf(" % name)
        row = []
        for v in chans[c]:
            row.append(str(v))
            if len(row) == 12:
                out.append("        " + ", ".join(row) + ",")
                row = []
        if row:
            out.append("        " + ", ".join(row) + ",")
        out.append("    )")
        out.append("")
    out.append("}")
    print("\n".join(out))


if __name__ == "__main__":
    main(sys.argv[1])
